@url = http://localhost:3000/api/v1/

GET {{url}}cliente

###

GET {{url}}cliente?option=4

###
GET {{url}}producto

###

GET {{url}}producto?option=proxcatg
###
GET {{url}}venta

###productocantidad fechacantidad totalventa

GET {{url}}venta?option=totalventa